### ISSUE TITLE
Criar sidbar

### ISSUE THREAD

**Issue by Rubensjuniors** [Rubensjuniors/Clone-twitter#7]
- Criar sidbar do twiter com alguns campos

- [x] campo de pesquisa 
- [x] listar assutos em alta
- [x] listar perfils

**Comment by rubensmarques-hotmart** [comment]
estou providenciando

**Comment by rubensmarques-hotmart** [comment]
Feito #8

**Comment by Rubensjuniors** [comment]
Done
